@echo off

taskkill /F /IM OfficeClickToRun.exe /T > nul
taskkill /F /IM GoogleCrashHandler.exe /T > nul
taskkill /F /IM GoogleCrashHandler64.exe /T > nul
taskkill /F /IM Telegram.exe /T > nul
taskkill /F /IM Code.exe /T > nul
taskkill /F /IM chrome.exe /T > nul
taskkill /F /IM notepad.exe /T > nul
taskkill /F /IM 7zFM.exe /T > nul
taskkill /F /IM Discord.exe /T > nul
taskkill /F /IM WINWORD.EXE /T > nul
taskkill /F /IM EXCEL.EXE /T > nul
taskkill /F /IM POWERPNT.EXE /T > nul
taskkill /F /IM Notion.exe /T > nul
taskkill /F /IM vlc.exe /T > nul
taskkill /F /IM xampp-control.exe /T > nul
taskkill /F /IM cmd.exe /T > nul
taskkill /F /IM SearchApp.exe /T > nul
taskkill /F /IM Postman.exe /T > nul
taskkill /F /IM obs64.exe /T > nul
taskkill /F /IM GitHubDesktop.exe /T > nul
taskkill /F /IM wpscenter.exe /T > nul
taskkill /F /IM wpscloudsvr.exe /T > nul
taskkill /F /IM vmware-authd.exe /T > nul
taskkill /F /IM vmnetdhcp.exe /T > nul
taskkill /F /IM vmnat.exe /T > nul
taskkill /F /IM vmware-usbarbitrator64.exe /T > nul
taskkill /F /IM vmware-unity-helper.exe /T > nul
taskkill /F /IM vmware.exe /T > nul
taskkill /F /IM vmware-tray.exe /T > nul