    Stop-Process -Name "OfficeClickToRun" -Force
    Stop-Process -Name "GoogleCrashHandler" -Force
    Stop-Process -Name "GoogleCrashHandler64" -Force
    Stop-Process -Name "Telegram" -Force
    Stop-Process -Name "Code" -Force
    Stop-Process -Name "chrome" -Force
    Stop-Process -Name "notepad" -Force
    Stop-Process -Name "7zFM" -Force
    Stop-Process -Name "Discord" -Force
    Stop-Process -Name "WINWORD" -Force
    Stop-Process -Name "EXCEL" -Force
    Stop-Process -Name "POWERPNT" -Force
    Stop-Process -Name "Notion" -Force
    Stop-Process -Name "vlc" -Force
    Stop-Process -Name "xampp-control" -Force
    Stop-Process -Name "cmd" -Force
    Stop-Process -Name "SearchApp" -Force
    Stop-Process -Name "Postman" -Force
    Stop-Process -Name "obs64" -Force
    Stop-Process -Name "GitHubDesktop" -Force
    Stop-Process -Name "wpscenter" -Force
    Stop-Process -Name "wpscloudsvr" -Force
    Stop-Process -Name "vmware-authd" -Force
    Stop-Process -Name "vmnetdhcp" -Force
    Stop-Process -Name "vmnat" -Force
    Stop-Process -Name "vmware-usbarbitrator64" -Force
    Stop-Process -Name "vmware-unity-helper" -Force
    Stop-Process -Name "vmware" -Force
    Stop-Process -Name "vmware-tray" -Force